import "@fortawesome/fontawesome-svg-core/styles.css"
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat, Open_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// New fonts
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Portfolio - CodeWithDeep",
  description: "Generated by create next app",
};

// export const metadata = {
//   title: "Deepankar Singh | Portfolio",
//   description: "Full-stack developer skilled in React, Next.js, Tailwind CSS, and Data Engineering. Check out my projects and experience.",
//   keywords: ["Deepankar Singh", "Portfolio", "React", "Next.js", "Tailwind CSS", "Full Stack Developer", "Data Engineer"],
//   authors: [{ name: "Deepankar Singh" }],
//   openGraph: {
//     title: "Deepankar Singh | Portfolio",
//     description: "Explore my projects, skills, and experience in web development and data engineering.",
//     url: "https://your-portfolio-url.com", // replace with your deployed URL
//     siteName: "Deepankar Singh Portfolio",
//     images: [
//       {
//         url: "https://your-portfolio-url.com/og-image.png", // add your OG image
//         width: 1200,
//         height: 630,
//         alt: "Deepankar Singh Portfolio",
//       },
//     ],
//     locale: "en_US",
//     type: "website",
//   },
//   twitter: {
//     card: "summary_large_image",
//     title: "Deepankar Singh | Portfolio",
//     description: "Check out my work in full-stack development and data engineering.",
//     creator: "@your_twitter_handle", // if you have Twitter
//     images: ["https://your-portfolio-url.com/og-image.png"],
//   },
//   icons: {
//     icon: "/favicon.ico", // make sure you have this in public/
//   },
// };


import ClientWrapper from "./ClientWrapper";

export default function RootLayout({ children }) {
  return (
    <html lang="en"
      suppressHydrationWarning="true"
      data-qb-installed="true"
      className="scroll-smooth"
    >
      <body className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${openSans.variable}`}>
        <ClientWrapper>{children}</ClientWrapper>
        {/* {children} */}
      </body>
    </html>
  );
}